services:
  - type: web
    name: backend
    runtime: java
    plan: free
    rootDir: backend
    buildCommand: mvn clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: PORT
        value: 8082

  - type: web
    name: face-ai
    runtime: python
    plan: free
    rootDir: face-ai
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

  - type: web
    name: frontend
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://backend.onrender.com