services:
  - type: web
    name: backend
    runtime: docker
    plan: free
    rootDir: backend
    envVars:
      - key: PORT
        value: 8082
      - key: FACE_AI_HOST
        fromService:
          type: web
          name: face-ai
          property: host
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d75li5kr85hc73cos150-a/faceattendence_db
      - key: SPRING_DATASOURCE_USERNAME
        value: faceattendence_db_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: THBtE0vrM5ZztSzAQhcTLGEyemkdMr0P

  - type: web
    name: face-ai
    runtime: python
    plan: free
    rootDir: face-ai
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py

  - type: web
    name: frontend
    runtime: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://backend.onrender.com